--AUTHOR: ANSAL MUHAMMED
--ASSIGNMENT 4 : LAB 4
--STUDENT ID: 100881383
--INFT2100


-- DROP SEQUENCE IF EXISTS calls_id;
-- CREATE SEQUENCE calls_id START 1000;

-- DROP TABLE IF EXISTS calls;
CREATE TABLE IF NOT EXISTS calls
(
    CallId SERIAL PRIMARY KEY,
    CalledOn TIMESTAMP NOT NULL,
    Notes VARCHAR(20),
    ClientsId INT NOT NULL,
    FOREIGN KEY (ClientsId) REFERENCES clients (ClientId)
);

SELECT * FROM calls;